export const mockedMovieList = [
  {
    adult: false,
    backdrop_path: "/wjQXZTlFM3PVEUmKf1sUajjygqT.jpg",
    genre_ids: [878, 28, 53],
    genres: [{ id: 878, name: "Science Fiction" }],
    id: 581726,
    original_language: "en",
    original_title: "Infinite",
    overview:
      "Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",
    popularity: 5354.043,
    poster_path: "/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
    release_date: "2021-09-08",
    title: "Infinite",
    video: false,
    vote_average: 0,
    vote_count: 0,
  },
  {
    adult: false,
    backdrop_path: "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg",
    genre_ids: [28, 12, 80],
    genres: [{ id: 53, name: "Thriller" }],
    id: 385128,
    original_language: "en",
    original_title: "F9",
    overview:
      "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
    popularity: 4332.422,
    poster_path: "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
    release_date: "2021-05-19",
    title: "F9",
    video: false,
    vote_average: 7.9,
    vote_count: 234,
  },
  {
    adult: false,
    backdrop_path: "/70AV2Xx5FQYj20labp0EGdbjI6E.jpg",
    genre_ids: [80, 28, 53],
    genres: [{ id: 28, name: "Action" }],
    id: 637649,
    original_language: "en",
    original_title: "Wrath of Man",
    overview:
      "A cold and mysterious new security guard for a Los Angeles cash truck company surprises his co-workers when he unleashes precision skills during a heist. The crew is left wondering who he is and where he came from. Soon, the marksman's ultimate motive becomes clear as he takes dramatic and irrevocable steps to settle a score.",
    popularity: 2625.795,
    poster_path: "/M7SUK85sKjaStg4TKhlAVyGlz3.jpg",
    release_date: "2021-04-22",
    title: "Wrath of Man",
    video: false,
    vote_average: 7.8,
    vote_count: 1110,
  },
];

export const mockedMovieData = {
  adult: false,
  backdrop_path: "/wjQXZTlFM3PVEUmKf1sUajjygqT.jpg",
  belongs_to_collection: null,
  budget: 0,
  genres: [
    { id: 878, name: "Science Fiction" },
    { id: 28, name: "Action" },
    { id: 53, name: "Thriller" },
  ],
  homepage:
    "https://www.paramountplus.com/movies/infinite/gkYk2Ju73QiIYX8TrooFblbsaUfPugRz/",
  id: 581726,
  imdb_id: "tt6654210",
  original_language: "en",
  original_title: "Infinite",
  overview:
    "Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",
  popularity: 5354.043,
  poster_path: "/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
  production_companies: [
    {
      id: 435,
      logo_path: "/AjzK0s2w1GtLfR4hqCjVSYi0Sr8.png",
      name: "Di Bonaventura Pictures",
      origin_country: "US",
    },
    {
      id: 4,
      logo_path: "/fycMZt242LVjagMByZOLUGbCvv3.png",
      name: "Paramount",
      origin_country: "US",
    },
    {
      id: 8537,
      logo_path: null,
      name: "Closest to the Hole Productions",
      origin_country: "US",
    },
    {
      id: 114732,
      logo_path: "/tNCbisMxO5mX2X2bOQxHHQZVYnT.png",
      name: "New Republic Pictures",
      origin_country: "US",
    },
    { id: 8151, logo_path: null, name: "Fuqua Films", origin_country: "US" },
  ],
  production_countries: [
    { iso_3166_1: "US", name: "United States of America" },
  ],
  release_date: "2021-09-08",
  revenue: 0,
  runtime: 106,
  spoken_languages: [
    { english_name: "English", iso_639_1: "en", name: "English" },
  ],
  status: "Released",
  tagline: "Grief. Hallucinations. Pride. Visions & Reminiscence",
  title: "Infinite2",
  video: false,
  vote_average: 0,
  vote_count: 0,
};
